import 'package:dungeon_store/constants.dart';
import 'package:dungeon_store/widgets/clase_widget.dart';
import 'package:flutter/material.dart';

class ClasesPage extends StatelessWidget {
  final clases = [
    {
      'icono': 'class_warrior.png',
      'nombre': 'Guerrero',
      'nameSize': 36.0,
      'info':
          'Los guerreros se equipan con cuidado para el combate y se enfrentan a sus enemigos de frente, dejando que los ataques resbalen contra su pesada armadura. Usan diversas tácticas de combate y una gran variedad de tipos de armas para proteger a los combatientes menos hábiles.',
      'raza1': 'humano_hombre.png',
      'raza2': 'orco_hombre.png',
      'raza3': 'enano_hombre.png',
      'raza4': 'undead_hombre.png',
      'raza5': 'nelf_hombre.png',
      'raza6': 'tauren_hombre.png',
      'raza7': 'gnomo_hombre.png',
      'raza8': 'troll_hombre.png',
      'raza9': 'draenei_hombre.png',
      'raza10': 'raza_empty.png',
    },
    {
      'icono': 'class_paladin.png',
      'nombre': 'Paladin',
      'nameSize': 36.0,
      'info':
          'Estos guerreros sagrados van equipados con armadura de placas para poder enfrentarse a los enemigos más duros y la bendición de la Luz les permite sanar heridas y, en algunos casos, incluso devolver la vida a los muertos.',
      'raza1': 'humano_hombre.png',
      'raza2': 'enano_hombre.png',
      'raza3': 'draenei_hombre.png',
      'raza4': 'blef_hombre.png',
      'raza5': 'raza_empty.png',
      'raza6': 'raza_empty.png',
      'raza7': 'raza_empty.png',
      'raza8': 'raza_empty.png',
      'raza9': 'raza_empty.png',
      'raza10': 'raza_empty.png',
    },
    {
      'icono': 'class_hunter.png',
      'nombre': 'Cazador',
      'nameSize': 36.0,
      'info':
          'Los cazadores luchan contra sus enemigos a distancia o de cerca y ordenan a sus mascotas que ataquen mientras preparan sus flechas, disparan sus armas de fuego o blanden sus armas cuerpo a cuerpo.',
      'raza1': 'enano_hombre.png',
      'raza2': 'nelf_hombre.png',
      'raza3': 'draenei_hombre.png',
      'raza4': 'orco_hombre.png',
      'raza5': 'tauren_hombre.png',
      'raza6': 'troll_hombre.png',
      'raza7': 'blef_hombre.png',
      'raza8': 'raza_empty.png',
      'raza9': 'raza_empty.png',
      'raza10': 'raza_empty.png',
    },
    {
      'icono': 'class_rogue.png',
      'nombre': 'Picaro',
      'nameSize': 36.0,
      'info':
          'Los pícaros a menudo inician sus batallas entre las sombras, comenzando con sanguinarios golpes cuerpo a cuerpo. En batallas largas, usan ataques sucesivos, cuidadosamente seleccionados para preparar al enemigo para el golpe final.',
      'raza1': 'humano_hombre.png',
      'raza2': 'enano_hombre.png',
      'raza3': 'nelf_hombre.png',
      'raza4': 'gnomo_hombre.png',
      'raza5': 'orco_hombre.png',
      'raza6': 'undead_hombre.png',
      'raza7': 'troll_hombre.png',
      'raza8': 'blef_hombre.png',
      'raza9': 'raza_empty.png',
      'raza10': 'raza_empty.png',
    },
    {
      'icono': 'class_priest.png',
      'nombre': 'Sacerdote',
      'nameSize': 36.0,
      'info':
          'Los sacerdotes están entregados a lo espiritual y expresan su inquebrantable fe sirviendo a la gente. Los sacerdotes usan poderosa magia de sanación para asegurarse de que tanto ellos como sus compañeros no son derribados.',
      'raza1': 'humano_hombre.png',
      'raza2': 'enano_hombre.png',
      'raza3': 'nelf_hombre.png',
      'raza4': 'draenei_hombre.png',
      'raza5': 'undead_hombre.png',
      'raza6': 'troll_hombre.png',
      'raza7': 'blef_hombre.png',
      'raza8': 'raza_empty.png',
      'raza9': 'raza_empty.png',
      'raza10': 'raza_empty.png',
    },
    {
      'icono': 'class_deathknight.png',
      'nombre': 'Caballero de la Muerte',
      'nameSize': 30.0,
      'info':
          'Los caballeros de la Muerte se enfrentan a sus enemigos de cerca, asestando golpes con sus armas con magia oscura que vuelve a los enemigos vulnerables o les inflige daño con poder oscuro.',
      'raza1': 'humano_hombre.png',
      'raza2': 'orco_hombre.png',
      'raza3': 'enano_hombre.png',
      'raza4': 'undead_hombre.png',
      'raza5': 'nelf_hombre.png',
      'raza6': 'tauren_hombre.png',
      'raza7': 'gnomo_hombre.png',
      'raza8': 'troll_hombre.png',
      'raza9': 'draenei_hombre.png',
      'raza10': 'blef_hombre.png',
    },
    {
      'icono': 'class_shaman.png',
      'nombre': 'Chaman',
      'nameSize': 36.0,
      'info':
          'Durante el combate, el chamán coloca totems de control y daño en el suelo para maximizar su efectividad y ponerle las cosas más difíciles a los enemigos Los chamanes son lo suficientemente versátiles para luchar contra los enemigos de cerca o a distancia.',
      'raza1': 'orco_hombre.png',
      'raza2': 'tauren_hombre.png',
      'raza3': 'troll_hombre.png',
      'raza4': 'draenei_hombre.png',
      'raza5': 'raza_empty.png',
      'raza6': 'raza_empty.png',
      'raza7': 'raza_empty.png',
      'raza8': 'raza_empty.png',
      'raza9': 'raza_empty.png',
      'raza10': 'raza_empty.png',
    },
    {
      'icono': 'class_mage.png',
      'nombre': 'Mago',
      'nameSize': 36.0,
      'info':
          'Los magos destruyen a sus enemigos con encantamientos arcanos. Aunque controlan poderosos hechizos ofensivos, los magos son frágiles y su armadura es ligera, lo que los hace particularmente vulnerables a los ataques a corta distancia.',
      'raza1': 'humano_hombre.png',
      'raza2': 'gnomo_hombre.png',
      'raza3': 'draenei_hombre.png',
      'raza4': 'undead_hombre.png',
      'raza5': 'troll_hombre.png',
      'raza6': 'blef_hombre.png',
      'raza7': 'raza_empty.png',
      'raza8': 'raza_empty.png',
      'raza9': 'raza_empty.png',
      'raza10': 'raza_empty.png',
    },
    {
      'icono': 'class_warlock.png',
      'nombre': 'Brujo',
      'nameSize': 36.0,
      'info':
          'Los brujos son expertos en invocar a sus aliados ante sí, ya sean dichos aliados otros héroes o demonios sanguinarios. Los brujos vinculan demonios a su voluntad, que defenderán a sus maestros con sus vidas o matarán a todos sus enemigos.',
      'raza1': 'humano_hombre.png',
      'raza2': 'gnomo_hombre.png',
      'raza3': 'orco_hombre.png',
      'raza4': 'undead_hombre.png',
      'raza5': 'blef_hombre.png',
      'raza6': 'raza_empty.png',
      'raza7': 'raza_empty.png',
      'raza8': 'raza_empty.png',
      'raza9': 'raza_empty.png',
      'raza10': 'raza_empty.png',
    },
    {
      'icono': 'class_druid.png',
      'nombre': 'Druida',
      'nameSize': 36.0,
      'info':
          'Los druidas controlan los enormes poderes de la naturaleza para mantener el equilibrio y proteger la vida.  Poseen una gran variedad de estilos de combate. Pueden llevar a cabo todos los roles: sanación, tanque, daño cuerpo a cuerpo y daño a distancia.',
      'raza1': 'nelf_hombre.png',
      'raza2': 'tauren_hombre.png',
      'raza3': 'raza_empty.png',
      'raza4': 'raza_empty.png',
      'raza5': 'raza_empty.png',
      'raza6': 'raza_empty.png',
      'raza7': 'raza_empty.png',
      'raza8': 'raza_empty.png',
      'raza9': 'raza_empty.png',
      'raza10': 'raza_empty.png',
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Clases'),
      ),
      body: ListView(
        children: clases.map(
          (e) {
            return ClaseWidget(
              icono: e['icono'] as String,
              nombre: e['nombre'] as String,
              nameSize: e['nameSize'] as double,
              info: e['info'] as String,
              raza1: e['raza1'] as String,
              raza2: e['raza2'] as String,
              raza3: e['raza3'] as String,
              raza4: e['raza4'] as String,
              raza5: e['raza5'] as String,
              raza6: e['raza6'] as String,
              raza7: e['raza7'] as String,
              raza8: e['raza8'] as String,
              raza9: e['raza9'] as String,
              raza10: e['raza10'] as String,
            );
          },
        ).toList(),
      ),
    );
  }
}
